[package]
name = "playdate_sys"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = { version = "0.2.155", default-features = false, features = [
  "const-extern-fn",
] }

[build-dependencies]
bindgen = "0.69.4"
