[package]
name = "example_app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
playdate = { path = "../playdate" }
playdate_init = { path = "../playdate_init" }
playdate_sys = { path = "../playdate_sys" }
